{"name": "test_sample2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 4", "trace": "def test_sample2():\n>       assert  5==4\nE       assert 5 == 4\n\nAPI_Python\\test_api_2.py:35: AssertionError"}, "start": 1702397386579, "stop": 1702397386579, "uuid": "dccfcb93-1933-45fb-9e92-27d7e468638a", "historyId": "878204a3f7dd8c036c65fb12fb1d6423", "testCaseId": "878204a3f7dd8c036c65fb12fb1d6423", "fullName": "API_Python.test_api_2#test_sample2", "labels": [{"name": "parentSuite", "value": "API_Python"}, {"name": "suite", "value": "test_api_2"}, {"name": "host", "value": "LAPTOP-CTE77PGL"}, {"name": "thread", "value": "19920-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API_Python.test_api_2"}]}